export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SETHISTORY = "SETHISTORY";
export const ADDHISTORY = "ADDHISTORY";
export const DELHISTORY = "DELHISTORY";
export const ADDWATCHLATER = "ADDWATERLATER";
export const DELWATCHLATER = "DELWATCHLATER";
export const ADDLIKEDVIDEO = "ADDLIKEDVIDEO";
export const DELLIKEDVIDEO = "DELLIKEDVIDEO";

export const ADDPLAYLIST = "ADDPLAYLIST";
export const DELPLAYLIST = "DELPLAYLIST";
export const ADDPLAYLISTVIDEO = "ADDPLAYLISTVIDEO";
export const DELPLAYLISTVIDEO = "DELPLAYLISTVIDEO";
