export { Home } from "./Home";
export { Trending } from "./Trending";
export { History } from "./History";
export { MyPlaylist } from "./MyPlaylist";
export { WatchLater } from "./WatchLater";
export { LikedVids } from "./LikedVids";
export { Settings } from "./Settings";
export { SingleVideo } from "./SingleVideo";
export { SinglePlaylist } from "./SinglePlaylist";
